<?php

namespace Santosdave\Travelport\System;

use Santosdave\Travelport\TravelportClient;

class SystemService extends TravelportClient
{

    /**
     * @var array $classmap The defined classes
     */
    private static $classmap = array (
  'NextResultReference' => 'Santosdave\\Travelport\\System\\NextResultReference',
  'Airport' => 'Santosdave\\Travelport\\System\\Airport',
  'VendorLocation' => 'Santosdave\\Travelport\\System\\VendorLocation',
  'typeVendorLocation' => 'Santosdave\\Travelport\\System\\typeVendorLocation',
  'AgencySellInfo' => 'Santosdave\\Travelport\\System\\AgencySellInfo',
  'AgencyInfo' => 'Santosdave\\Travelport\\System\\AgencyInfo',
  'AgentAction' => 'Santosdave\\Travelport\\System\\AgentAction',
  'AirExchangeInfo' => 'Santosdave\\Travelport\\System\\AirExchangeInfo',
  'TotalPenaltyTaxInfo' => 'Santosdave\\Travelport\\System\\TotalPenaltyTaxInfo',
  'TicketFeeInfo' => 'Santosdave\\Travelport\\System\\TicketFeeInfo',
  'Auxdata' => 'Santosdave\\Travelport\\System\\Auxdata',
  'Entry' => 'Santosdave\\Travelport\\System\\Entry',
  'Carrier' => 'Santosdave\\Travelport\\System\\Carrier',
  'Provider' => 'Santosdave\\Travelport\\System\\Provider',
  'Certificate' => 'Santosdave\\Travelport\\System\\Certificate',
  'Check' => 'Santosdave\\Travelport\\System\\Check',
  'City' => 'Santosdave\\Travelport\\System\\City',
  'CityOrAirport' => 'Santosdave\\Travelport\\System\\CityOrAirport',
  'CoordinateLocation' => 'Santosdave\\Travelport\\System\\CoordinateLocation',
  'RailLocation' => 'Santosdave\\Travelport\\System\\RailLocation',
  'Credentials' => 'Santosdave\\Travelport\\System\\Credentials',
  'CreditCard' => 'Santosdave\\Travelport\\System\\CreditCard',
  'CustomizedNameData' => 'Santosdave\\Travelport\\System\\CustomizedNameData',
  'DebitCard' => 'Santosdave\\Travelport\\System\\DebitCard',
  'Requisition' => 'Santosdave\\Travelport\\System\\Requisition',
  'MiscFormOfPayment' => 'Santosdave\\Travelport\\System\\MiscFormOfPayment',
  'SupplierLocator' => 'Santosdave\\Travelport\\System\\SupplierLocator',
  'typePaymentCard' => 'Santosdave\\Travelport\\System\\typePaymentCard',
  'CreditCardAuth' => 'Santosdave\\Travelport\\System\\CreditCardAuth',
  'typeGeneralReference' => 'Santosdave\\Travelport\\System\\typeGeneralReference',
  'typeFormOfPaymentPNRReference' => 'Santosdave\\Travelport\\System\\typeFormOfPaymentPNRReference',
  'FormOfPayment' => 'Santosdave\\Travelport\\System\\FormOfPayment',
  'EnettVan' => 'Santosdave\\Travelport\\System\\EnettVan',
  'typeVoucherInformation' => 'Santosdave\\Travelport\\System\\typeVoucherInformation',
  'UnitedNations' => 'Santosdave\\Travelport\\System\\UnitedNations',
  'DirectPayment' => 'Santosdave\\Travelport\\System\\DirectPayment',
  'AgentVoucher' => 'Santosdave\\Travelport\\System\\AgentVoucher',
  'typeAgencyPayment' => 'Santosdave\\Travelport\\System\\typeAgencyPayment',
  'FormOfPaymentRef' => 'Santosdave\\Travelport\\System\\FormOfPaymentRef',
  'Distance' => 'Santosdave\\Travelport\\System\\Distance',
  'Email' => 'Santosdave\\Travelport\\System\\Email',
  'MealRequest' => 'Santosdave\\Travelport\\System\\MealRequest',
  'Name' => 'Santosdave\\Travelport\\System\\Name',
  'ProviderARNKSegment' => 'Santosdave\\Travelport\\System\\ProviderARNKSegment',
  'PreviousSegment' => 'Santosdave\\Travelport\\System\\PreviousSegment',
  'NextSegment' => 'Santosdave\\Travelport\\System\\NextSegment',
  'PassiveInfo' => 'Santosdave\\Travelport\\System\\PassiveInfo',
  'BookingTraveler' => 'Santosdave\\Travelport\\System\\BookingTraveler',
  'BookingTravelerName' => 'Santosdave\\Travelport\\System\\BookingTravelerName',
  'NameRemark' => 'Santosdave\\Travelport\\System\\NameRemark',
  'PhoneNumber' => 'Santosdave\\Travelport\\System\\PhoneNumber',
  'ProviderReservationInfoRef' => 'Santosdave\\Travelport\\System\\ProviderReservationInfoRef',
  'ResponseMessage' => 'Santosdave\\Travelport\\System\\ResponseMessage',
  'State' => 'Santosdave\\Travelport\\System\\State',
  'Remark' => 'Santosdave\\Travelport\\System\\Remark',
  'SegmentRemark' => 'Santosdave\\Travelport\\System\\SegmentRemark',
  'RefundRemark' => 'Santosdave\\Travelport\\System\\RefundRemark',
  'GeneralRemark' => 'Santosdave\\Travelport\\System\\GeneralRemark',
  'CommissionRemark' => 'Santosdave\\Travelport\\System\\CommissionRemark',
  'ProviderReservationLevel' => 'Santosdave\\Travelport\\System\\ProviderReservationLevel',
  'PassengerTypeLevel' => 'Santosdave\\Travelport\\System\\PassengerTypeLevel',
  'AccountingRemark' => 'Santosdave\\Travelport\\System\\AccountingRemark',
  'XMLRemark' => 'Santosdave\\Travelport\\System\\XMLRemark',
  'HostToken' => 'Santosdave\\Travelport\\System\\HostToken',
  'HostTokenList' => 'Santosdave\\Travelport\\System\\HostTokenList',
  'AppliedProfile' => 'Santosdave\\Travelport\\System\\AppliedProfile',
  'typeGuaranteeInformation' => 'Santosdave\\Travelport\\System\\typeGuaranteeInformation',
  'AccountCode' => 'Santosdave\\Travelport\\System\\AccountCode',
  'AirSearchParameters' => 'Santosdave\\Travelport\\System\\AirSearchParameters',
  'Commission' => 'Santosdave\\Travelport\\System\\Commission',
  'DeliveryInfo' => 'Santosdave\\Travelport\\System\\DeliveryInfo',
  'ShippingAddress' => 'Santosdave\\Travelport\\System\\ShippingAddress',
  'ActionStatus' => 'Santosdave\\Travelport\\System\\ActionStatus',
  'Endorsement' => 'Santosdave\\Travelport\\System\\Endorsement',
  'typeProviderReservationSpecificInfo' => 'Santosdave\\Travelport\\System\\typeProviderReservationSpecificInfo',
  'LoyaltyCard' => 'Santosdave\\Travelport\\System\\LoyaltyCard',
  'DiscountCard' => 'Santosdave\\Travelport\\System\\DiscountCard',
  'OperatedBy' => 'Santosdave\\Travelport\\System\\OperatedBy',
  'Penalty' => 'Santosdave\\Travelport\\System\\Penalty',
  'Restriction' => 'Santosdave\\Travelport\\System\\Restriction',
  'SeatAssignment' => 'Santosdave\\Travelport\\System\\SeatAssignment',
  'AirSeatAssignment' => 'Santosdave\\Travelport\\System\\AirSeatAssignment',
  'RailSeatAssignment' => 'Santosdave\\Travelport\\System\\RailSeatAssignment',
  'Characteristic' => 'Santosdave\\Travelport\\System\\Characteristic',
  'ServiceData' => 'Santosdave\\Travelport\\System\\ServiceData',
  'ServiceInfo' => 'Santosdave\\Travelport\\System\\ServiceInfo',
  'SSR' => 'Santosdave\\Travelport\\System\\SSR',
  'TravelerType' => 'Santosdave\\Travelport\\System\\TravelerType',
  'PaymentRef' => 'Santosdave\\Travelport\\System\\PaymentRef',
  'BookingTravelerRef' => 'Santosdave\\Travelport\\System\\BookingTravelerRef',
  'DiscountCardRef' => 'Santosdave\\Travelport\\System\\DiscountCardRef',
  'DriversLicenseRef' => 'Santosdave\\Travelport\\System\\DriversLicenseRef',
  'LoyaltyCardRef' => 'Santosdave\\Travelport\\System\\LoyaltyCardRef',
  'typeRemark' => 'Santosdave\\Travelport\\System\\typeRemark',
  'UnassociatedRemark' => 'Santosdave\\Travelport\\System\\UnassociatedRemark',
  'typeRemarkWithTravelerRef' => 'Santosdave\\Travelport\\System\\typeRemarkWithTravelerRef',
  'CustomerID' => 'Santosdave\\Travelport\\System\\CustomerID',
  'BaseReservation' => 'Santosdave\\Travelport\\System\\BaseReservation',
  'MCO' => 'Santosdave\\Travelport\\System\\MCO',
  'MCOText' => 'Santosdave\\Travelport\\System\\MCOText',
  'typeFreeFormText' => 'Santosdave\\Travelport\\System\\typeFreeFormText',
  'MCOPriceData' => 'Santosdave\\Travelport\\System\\MCOPriceData',
  'PassengerInfo' => 'Santosdave\\Travelport\\System\\PassengerInfo',
  'MCOInformation' => 'Santosdave\\Travelport\\System\\MCOInformation',
  'MCOExchangeInfo' => 'Santosdave\\Travelport\\System\\MCOExchangeInfo',
  'MCOFeeInfo' => 'Santosdave\\Travelport\\System\\MCOFeeInfo',
  'MCORemark' => 'Santosdave\\Travelport\\System\\MCORemark',
  'StockControl' => 'Santosdave\\Travelport\\System\\StockControl',
  'ExchangedCoupon' => 'Santosdave\\Travelport\\System\\ExchangedCoupon',
  'typeTaxInfo' => 'Santosdave\\Travelport\\System\\typeTaxInfo',
  'TaxDetail' => 'Santosdave\\Travelport\\System\\TaxDetail',
  'MetaData' => 'Santosdave\\Travelport\\System\\MetaData',
  'RoleInfo' => 'Santosdave\\Travelport\\System\\RoleInfo',
  'OSI' => 'Santosdave\\Travelport\\System\\OSI',
  'Segment' => 'Santosdave\\Travelport\\System\\Segment',
  'TravelSegment' => 'Santosdave\\Travelport\\System\\TravelSegment',
  'SearchEvent' => 'Santosdave\\Travelport\\System\\SearchEvent',
  'SearchTicketing' => 'Santosdave\\Travelport\\System\\SearchTicketing',
  'SearchPassenger' => 'Santosdave\\Travelport\\System\\SearchPassenger',
  'SpecialEquipment' => 'Santosdave\\Travelport\\System\\SpecialEquipment',
  'ContinuityCheckOverride' => 'Santosdave\\Travelport\\System\\ContinuityCheckOverride',
  'typeAgentInfo' => 'Santosdave\\Travelport\\System\\typeAgentInfo',
  'typeResultMessage' => 'Santosdave\\Travelport\\System\\typeResultMessage',
  'Location' => 'Santosdave\\Travelport\\System\\Location',
  'typeSearchTimeSpec' => 'Santosdave\\Travelport\\System\\typeSearchTimeSpec',
  'typeStructuredAddress' => 'Santosdave\\Travelport\\System\\typeStructuredAddress',
  'typeTimeRange' => 'Santosdave\\Travelport\\System\\typeTimeRange',
  'typeRateDescription' => 'Santosdave\\Travelport\\System\\typeRateDescription',
  'MediaItem' => 'Santosdave\\Travelport\\System\\MediaItem',
  'PointOfSale' => 'Santosdave\\Travelport\\System\\PointOfSale',
  'BookingTravelerInfo' => 'Santosdave\\Travelport\\System\\BookingTravelerInfo',
  'TravelInfo' => 'Santosdave\\Travelport\\System\\TravelInfo',
  'BookingSource' => 'Santosdave\\Travelport\\System\\BookingSource',
  'typeSearchLocation' => 'Santosdave\\Travelport\\System\\typeSearchLocation',
  'typeTimeSpec' => 'Santosdave\\Travelport\\System\\typeTimeSpec',
  'typeSpecificTime' => 'Santosdave\\Travelport\\System\\typeSpecificTime',
  'typeFlexibleTimeSpec' => 'Santosdave\\Travelport\\System\\typeFlexibleTimeSpec',
  'SearchExtraDays' => 'Santosdave\\Travelport\\System\\SearchExtraDays',
  'typePassengerType' => 'Santosdave\\Travelport\\System\\typePassengerType',
  'Guarantee' => 'Santosdave\\Travelport\\System\\Guarantee',
  'OtherGuaranteeInfo' => 'Santosdave\\Travelport\\System\\OtherGuaranteeInfo',
  'Payment' => 'Santosdave\\Travelport\\System\\Payment',
  'ServiceRuleType' => 'Santosdave\\Travelport\\System\\ServiceRuleType',
  'ApplicationRules' => 'Santosdave\\Travelport\\System\\ApplicationRules',
  'ApplicationLevel' => 'Santosdave\\Travelport\\System\\ApplicationLevel',
  'ApplicationLimits' => 'Santosdave\\Travelport\\System\\ApplicationLimits',
  'ModifyRules' => 'Santosdave\\Travelport\\System\\ModifyRules',
  'ModifyRule' => 'Santosdave\\Travelport\\System\\ModifyRule',
  'SecondaryTypeRules' => 'Santosdave\\Travelport\\System\\SecondaryTypeRules',
  'SecondaryTypeRule' => 'Santosdave\\Travelport\\System\\SecondaryTypeRule',
  'OptionalServiceApplicationLimitType' => 'Santosdave\\Travelport\\System\\OptionalServiceApplicationLimitType',
  'FormattedTextTextType' => 'Santosdave\\Travelport\\System\\FormattedTextTextType',
  'CorporateDiscountID' => 'Santosdave\\Travelport\\System\\CorporateDiscountID',
  'AgencyContactInfo' => 'Santosdave\\Travelport\\System\\AgencyContactInfo',
  'typeLocation' => 'Santosdave\\Travelport\\System\\typeLocation',
  'typeProfileRef' => 'Santosdave\\Travelport\\System\\typeProfileRef',
  'ServiceFeeTaxInfo' => 'Santosdave\\Travelport\\System\\ServiceFeeTaxInfo',
  'ServiceFeeInfo' => 'Santosdave\\Travelport\\System\\ServiceFeeInfo',
  'LinkedUniversalRecord' => 'Santosdave\\Travelport\\System\\LinkedUniversalRecord',
  'typeDateRange' => 'Santosdave\\Travelport\\System\\typeDateRange',
  'MarketingInformation' => 'Santosdave\\Travelport\\System\\MarketingInformation',
  'Postscript' => 'Santosdave\\Travelport\\System\\Postscript',
  'typeAgencyHierarchyReference' => 'Santosdave\\Travelport\\System\\typeAgencyHierarchyReference',
  'typeAgencyHierarchyLongReference' => 'Santosdave\\Travelport\\System\\typeAgencyHierarchyLongReference',
  'DriversLicense' => 'Santosdave\\Travelport\\System\\DriversLicense',
  'typeAssociatedRemarkWithSegmentRef' => 'Santosdave\\Travelport\\System\\typeAssociatedRemarkWithSegmentRef',
  'typeAssociatedRemark' => 'Santosdave\\Travelport\\System\\typeAssociatedRemark',
  'ShopInformation' => 'Santosdave\\Travelport\\System\\ShopInformation',
  'SearchRequest' => 'Santosdave\\Travelport\\System\\SearchRequest',
  'FlightsOffered' => 'Santosdave\\Travelport\\System\\FlightsOffered',
  'PolicyInformation' => 'Santosdave\\Travelport\\System\\PolicyInformation',
  'ReasonCode' => 'Santosdave\\Travelport\\System\\ReasonCode',
  'AgencyInformation' => 'Santosdave\\Travelport\\System\\AgencyInformation',
  'AccountInformation' => 'Santosdave\\Travelport\\System\\AccountInformation',
  'TravelerInformation' => 'Santosdave\\Travelport\\System\\TravelerInformation',
  'EmergencyContact' => 'Santosdave\\Travelport\\System\\EmergencyContact',
  'CustomProfileInformation' => 'Santosdave\\Travelport\\System\\CustomProfileInformation',
  'FileFinishingInfo' => 'Santosdave\\Travelport\\System\\FileFinishingInfo',
  'BillingPointOfSaleInfo' => 'Santosdave\\Travelport\\System\\BillingPointOfSaleInfo',
  'AgentIDOverride' => 'Santosdave\\Travelport\\System\\AgentIDOverride',
  'OverridePCC' => 'Santosdave\\Travelport\\System\\OverridePCC',
  'typeKeyword' => 'Santosdave\\Travelport\\System\\typeKeyword',
  'typeSubKey' => 'Santosdave\\Travelport\\System\\typeSubKey',
  'Keyword' => 'Santosdave\\Travelport\\System\\Keyword',
  'BookingDates' => 'Santosdave\\Travelport\\System\\BookingDates',
  'PaymentRestriction' => 'Santosdave\\Travelport\\System\\PaymentRestriction',
  'RequiredField' => 'Santosdave\\Travelport\\System\\RequiredField',
  'CardRestriction' => 'Santosdave\\Travelport\\System\\CardRestriction',
  'AddressRestriction' => 'Santosdave\\Travelport\\System\\AddressRestriction',
  'SSRInfo' => 'Santosdave\\Travelport\\System\\SSRInfo',
  'typeNonAirReservationRef' => 'Santosdave\\Travelport\\System\\typeNonAirReservationRef',
  'typeSegmentRef' => 'Santosdave\\Travelport\\System\\typeSegmentRef',
  'InvoiceRemark' => 'Santosdave\\Travelport\\System\\InvoiceRemark',
  'RequestKeyMappings' => 'Santosdave\\Travelport\\System\\RequestKeyMappings',
  'KeyMapping' => 'Santosdave\\Travelport\\System\\KeyMapping',
  'ReservationName' => 'Santosdave\\Travelport\\System\\ReservationName',
  'NameOverride' => 'Santosdave\\Travelport\\System\\NameOverride',
  'APIProvider' => 'Santosdave\\Travelport\\System\\APIProvider',
  'AvailablePseudoCityCode' => 'Santosdave\\Travelport\\System\\AvailablePseudoCityCode',
  'TransactionType' => 'Santosdave\\Travelport\\System\\TransactionType',
  'Air' => 'Santosdave\\Travelport\\System\\Air',
  'typeTransactionsAllowed' => 'Santosdave\\Travelport\\System\\typeTransactionsAllowed',
  'typeBookingTransactionsAllowed' => 'Santosdave\\Travelport\\System\\typeBookingTransactionsAllowed',
  'ThirdPartyInformation' => 'Santosdave\\Travelport\\System\\ThirdPartyInformation',
  'TravelComplianceData' => 'Santosdave\\Travelport\\System\\TravelComplianceData',
  'PolicyCompliance' => 'Santosdave\\Travelport\\System\\PolicyCompliance',
  'ContractCompliance' => 'Santosdave\\Travelport\\System\\ContractCompliance',
  'PreferredSupplier' => 'Santosdave\\Travelport\\System\\PreferredSupplier',
  'LoyaltyProgram' => 'Santosdave\\Travelport\\System\\LoyaltyProgram',
  'typeErrorInfo' => 'Santosdave\\Travelport\\System\\typeErrorInfo',
  'PermittedProviders' => 'Santosdave\\Travelport\\System\\PermittedProviders',
  'ReviewBooking' => 'Santosdave\\Travelport\\System\\ReviewBooking',
  'typeCreditCardType' => 'Santosdave\\Travelport\\System\\typeCreditCardType',
  'PersonalGeography' => 'Santosdave\\Travelport\\System\\PersonalGeography',
  'Group' => 'Santosdave\\Travelport\\System\\Group',
  'SSRRef' => 'Santosdave\\Travelport\\System\\SSRRef',
  'ConsolidatorRemark' => 'Santosdave\\Travelport\\System\\ConsolidatorRemark',
  'PseudoCityCode' => 'Santosdave\\Travelport\\System\\PseudoCityCode',
  'BaseAsyncProviderSpecificResponse' => 'Santosdave\\Travelport\\System\\BaseAsyncProviderSpecificResponse',
  'typeProviderReservationDetail' => 'Santosdave\\Travelport\\System\\typeProviderReservationDetail',
  'CabinClass' => 'Santosdave\\Travelport\\System\\CabinClass',
  'SeatAttributes' => 'Santosdave\\Travelport\\System\\SeatAttributes',
  'SeatAttribute' => 'Santosdave\\Travelport\\System\\SeatAttribute',
  'typeKeyBasedReference' => 'Santosdave\\Travelport\\System\\typeKeyBasedReference',
  'InvoiceData' => 'Santosdave\\Travelport\\System\\InvoiceData',
  'BookingTravelerInformation' => 'Santosdave\\Travelport\\System\\BookingTravelerInformation',
  'OwnershipChange' => 'Santosdave\\Travelport\\System\\OwnershipChange',
  'IndustryStandardSSR' => 'Santosdave\\Travelport\\System\\IndustryStandardSSR',
  'PaymentAdvice' => 'Santosdave\\Travelport\\System\\PaymentAdvice',
  'EmailNotification' => 'Santosdave\\Travelport\\System\\EmailNotification',
  'typeTax' => 'Santosdave\\Travelport\\System\\typeTax',
  'typeFeeInfo' => 'Santosdave\\Travelport\\System\\typeFeeInfo',
  'TaxInfoRef' => 'Santosdave\\Travelport\\System\\TaxInfoRef',
  'QueuePlace' => 'Santosdave\\Travelport\\System\\QueuePlace',
  'QueueSelector' => 'Santosdave\\Travelport\\System\\QueueSelector',
  'BaseReq' => 'Santosdave\\Travelport\\System\\BaseReq',
  'BaseCoreReq' => 'Santosdave\\Travelport\\System\\BaseCoreReq',
  'BaseSearchReq' => 'Santosdave\\Travelport\\System\\BaseSearchReq',
  'BaseCoreSearchReq' => 'Santosdave\\Travelport\\System\\BaseCoreSearchReq',
  'BaseSearchRsp' => 'Santosdave\\Travelport\\System\\BaseSearchRsp',
  'BaseRsp' => 'Santosdave\\Travelport\\System\\BaseRsp',
  'BaseCreateReservationReq' => 'Santosdave\\Travelport\\System\\BaseCreateReservationReq',
  'ErrorInfo' => 'Santosdave\\Travelport\\System\\ErrorInfo',
  'BaseCreateWithFormOfPaymentReq' => 'Santosdave\\Travelport\\System\\BaseCreateWithFormOfPaymentReq',
  'PingReq' => 'Santosdave\\Travelport\\System\\PingReq',
  'PingRsp' => 'Santosdave\\Travelport\\System\\PingRsp',
  'SystemInfoReq' => 'Santosdave\\Travelport\\System\\SystemInfoReq',
  'SystemInfoRsp' => 'Santosdave\\Travelport\\System\\SystemInfoRsp',
  'TimeReq' => 'Santosdave\\Travelport\\System\\TimeReq',
  'TimeRsp' => 'Santosdave\\Travelport\\System\\TimeRsp',
  'SystemInfo' => 'Santosdave\\Travelport\\System\\SystemInfo',
  'BridgedBranch' => 'Santosdave\\Travelport\\System\\BridgedBranch',
  'ExternalCacheAccessReq' => 'Santosdave\\Travelport\\System\\ExternalCacheAccessReq',
  'RetrieveEntry' => 'Santosdave\\Travelport\\System\\RetrieveEntry',
  'DeleteEntry' => 'Santosdave\\Travelport\\System\\DeleteEntry',
  'ExternalCacheAccessRsp' => 'Santosdave\\Travelport\\System\\ExternalCacheAccessRsp',
  'CacheEntry' => 'Santosdave\\Travelport\\System\\CacheEntry',
);

    /**
     * @param array $options A array of config values
     * @param string $wsdl The wsdl file to use
     */
    public function __construct(array $options = array(), $wsdl = null)
    {
      foreach (self::$classmap as $key => $value) {
        if (!isset($options['classmap'][$key])) {
          $options['classmap'][$key] = $value;
        }
      }
      $options = array_merge(array (
  'features' => 1,
), $options);
      if (!$wsdl) {
        $wsdl = 'D:\efes.to\components\filippo-toso\travelport\builder/../src/Wsdls/system_v32_0/System.wsdl';
      }
      parent::__construct($wsdl, $options);
    }

    /**
     * @param TimeReq $parameters
     * @return TimeRsp
     */
    public function service(TimeReq $parameters)
    {
      return $this->__soapCall('service', array($parameters));
    }

}
