<?php

namespace Santosdave\Travelport\Vehicle;

use Santosdave\Travelport\TravelportClient;

class VehicleService extends TravelportClient
{

    /**
     * @var array $classmap The defined classes
     */
    private static $classmap = array (
  'SessionContext' => 'Santosdave\\Travelport\\Vehicle\\SessionContext',
  'SessTok' => 'Santosdave\\Travelport\\Vehicle\\SessTok',
  'SessProp' => 'Santosdave\\Travelport\\Vehicle\\SessProp',
  'NextResultReference' => 'Santosdave\\Travelport\\Vehicle\\NextResultReference',
  'Airport' => 'Santosdave\\Travelport\\Vehicle\\Airport',
  'VendorLocation' => 'Santosdave\\Travelport\\Vehicle\\VendorLocation',
  'typeVendorLocation' => 'Santosdave\\Travelport\\Vehicle\\typeVendorLocation',
  'AgencySellInfo' => 'Santosdave\\Travelport\\Vehicle\\AgencySellInfo',
  'AgencyInfo' => 'Santosdave\\Travelport\\Vehicle\\AgencyInfo',
  'AgentAction' => 'Santosdave\\Travelport\\Vehicle\\AgentAction',
  'AirExchangeInfo' => 'Santosdave\\Travelport\\Vehicle\\AirExchangeInfo',
  'TotalPenaltyTaxInfo' => 'Santosdave\\Travelport\\Vehicle\\TotalPenaltyTaxInfo',
  'TicketFeeInfo' => 'Santosdave\\Travelport\\Vehicle\\TicketFeeInfo',
  'Auxdata' => 'Santosdave\\Travelport\\Vehicle\\Auxdata',
  'Entry' => 'Santosdave\\Travelport\\Vehicle\\Entry',
  'Carrier' => 'Santosdave\\Travelport\\Vehicle\\Carrier',
  'Provider' => 'Santosdave\\Travelport\\Vehicle\\Provider',
  'Certificate' => 'Santosdave\\Travelport\\Vehicle\\Certificate',
  'Check' => 'Santosdave\\Travelport\\Vehicle\\Check',
  'City' => 'Santosdave\\Travelport\\Vehicle\\City',
  'CityOrAirport' => 'Santosdave\\Travelport\\Vehicle\\CityOrAirport',
  'CoordinateLocation' => 'Santosdave\\Travelport\\Vehicle\\CoordinateLocation',
  'RailLocation' => 'Santosdave\\Travelport\\Vehicle\\RailLocation',
  'Credentials' => 'Santosdave\\Travelport\\Vehicle\\Credentials',
  'CreditCard' => 'Santosdave\\Travelport\\Vehicle\\CreditCard',
  'CustomizedNameData' => 'Santosdave\\Travelport\\Vehicle\\CustomizedNameData',
  'DebitCard' => 'Santosdave\\Travelport\\Vehicle\\DebitCard',
  'Requisition' => 'Santosdave\\Travelport\\Vehicle\\Requisition',
  'MiscFormOfPayment' => 'Santosdave\\Travelport\\Vehicle\\MiscFormOfPayment',
  'SupplierLocator' => 'Santosdave\\Travelport\\Vehicle\\SupplierLocator',
  'typePaymentCard' => 'Santosdave\\Travelport\\Vehicle\\typePaymentCard',
  'CreditCardAuth' => 'Santosdave\\Travelport\\Vehicle\\CreditCardAuth',
  'typeGeneralReference' => 'Santosdave\\Travelport\\Vehicle\\typeGeneralReference',
  'typeFormOfPaymentPNRReference' => 'Santosdave\\Travelport\\Vehicle\\typeFormOfPaymentPNRReference',
  'FormOfPayment' => 'Santosdave\\Travelport\\Vehicle\\FormOfPayment',
  'BSPPayment' => 'Santosdave\\Travelport\\Vehicle\\BSPPayment',
  'ARCPayment' => 'Santosdave\\Travelport\\Vehicle\\ARCPayment',
  'EnettVan' => 'Santosdave\\Travelport\\Vehicle\\EnettVan',
  'typeVoucherInformation' => 'Santosdave\\Travelport\\Vehicle\\typeVoucherInformation',
  'UnitedNations' => 'Santosdave\\Travelport\\Vehicle\\UnitedNations',
  'DirectPayment' => 'Santosdave\\Travelport\\Vehicle\\DirectPayment',
  'AgentVoucher' => 'Santosdave\\Travelport\\Vehicle\\AgentVoucher',
  'typeAgencyPayment' => 'Santosdave\\Travelport\\Vehicle\\typeAgencyPayment',
  'FormOfPaymentRef' => 'Santosdave\\Travelport\\Vehicle\\FormOfPaymentRef',
  'Distance' => 'Santosdave\\Travelport\\Vehicle\\Distance',
  'Email' => 'Santosdave\\Travelport\\Vehicle\\Email',
  'MealRequest' => 'Santosdave\\Travelport\\Vehicle\\MealRequest',
  'Name' => 'Santosdave\\Travelport\\Vehicle\\Name',
  'ProviderARNKSegment' => 'Santosdave\\Travelport\\Vehicle\\ProviderARNKSegment',
  'PreviousSegment' => 'Santosdave\\Travelport\\Vehicle\\PreviousSegment',
  'NextSegment' => 'Santosdave\\Travelport\\Vehicle\\NextSegment',
  'PassiveInfo' => 'Santosdave\\Travelport\\Vehicle\\PassiveInfo',
  'BookingTraveler' => 'Santosdave\\Travelport\\Vehicle\\BookingTraveler',
  'BookingTravelerName' => 'Santosdave\\Travelport\\Vehicle\\BookingTravelerName',
  'NameRemark' => 'Santosdave\\Travelport\\Vehicle\\NameRemark',
  'PhoneNumber' => 'Santosdave\\Travelport\\Vehicle\\PhoneNumber',
  'ProviderReservationInfoRef' => 'Santosdave\\Travelport\\Vehicle\\ProviderReservationInfoRef',
  'ResponseMessage' => 'Santosdave\\Travelport\\Vehicle\\ResponseMessage',
  'State' => 'Santosdave\\Travelport\\Vehicle\\State',
  'Remark' => 'Santosdave\\Travelport\\Vehicle\\Remark',
  'SegmentRemark' => 'Santosdave\\Travelport\\Vehicle\\SegmentRemark',
  'RefundRemark' => 'Santosdave\\Travelport\\Vehicle\\RefundRemark',
  'GeneralRemark' => 'Santosdave\\Travelport\\Vehicle\\GeneralRemark',
  'CommissionRemark' => 'Santosdave\\Travelport\\Vehicle\\CommissionRemark',
  'ProviderReservationLevel' => 'Santosdave\\Travelport\\Vehicle\\ProviderReservationLevel',
  'PassengerTypeLevel' => 'Santosdave\\Travelport\\Vehicle\\PassengerTypeLevel',
  'AccountingRemark' => 'Santosdave\\Travelport\\Vehicle\\AccountingRemark',
  'XMLRemark' => 'Santosdave\\Travelport\\Vehicle\\XMLRemark',
  'HostToken' => 'Santosdave\\Travelport\\Vehicle\\HostToken',
  'HostTokenList' => 'Santosdave\\Travelport\\Vehicle\\HostTokenList',
  'AddSvc' => 'Santosdave\\Travelport\\Vehicle\\AddSvc',
  'AppliedProfile' => 'Santosdave\\Travelport\\Vehicle\\AppliedProfile',
  'typeGuaranteeInformation' => 'Santosdave\\Travelport\\Vehicle\\typeGuaranteeInformation',
  'AccountCode' => 'Santosdave\\Travelport\\Vehicle\\AccountCode',
  'AirSearchParameters' => 'Santosdave\\Travelport\\Vehicle\\AirSearchParameters',
  'Commission' => 'Santosdave\\Travelport\\Vehicle\\Commission',
  'DeliveryInfo' => 'Santosdave\\Travelport\\Vehicle\\DeliveryInfo',
  'ShippingAddress' => 'Santosdave\\Travelport\\Vehicle\\ShippingAddress',
  'ActionStatus' => 'Santosdave\\Travelport\\Vehicle\\ActionStatus',
  'Endorsement' => 'Santosdave\\Travelport\\Vehicle\\Endorsement',
  'typeProviderReservationSpecificInfo' => 'Santosdave\\Travelport\\Vehicle\\typeProviderReservationSpecificInfo',
  'LoyaltyCard' => 'Santosdave\\Travelport\\Vehicle\\LoyaltyCard',
  'DiscountCard' => 'Santosdave\\Travelport\\Vehicle\\DiscountCard',
  'OperatedBy' => 'Santosdave\\Travelport\\Vehicle\\OperatedBy',
  'Penalty' => 'Santosdave\\Travelport\\Vehicle\\Penalty',
  'Restriction' => 'Santosdave\\Travelport\\Vehicle\\Restriction',
  'SeatAssignment' => 'Santosdave\\Travelport\\Vehicle\\SeatAssignment',
  'AirSeatAssignment' => 'Santosdave\\Travelport\\Vehicle\\AirSeatAssignment',
  'RailSeatAssignment' => 'Santosdave\\Travelport\\Vehicle\\RailSeatAssignment',
  'Characteristic' => 'Santosdave\\Travelport\\Vehicle\\Characteristic',
  'ServiceData' => 'Santosdave\\Travelport\\Vehicle\\ServiceData',
  'ServiceInfo' => 'Santosdave\\Travelport\\Vehicle\\ServiceInfo',
  'SSR' => 'Santosdave\\Travelport\\Vehicle\\SSR',
  'TravelerType' => 'Santosdave\\Travelport\\Vehicle\\TravelerType',
  'PaymentRef' => 'Santosdave\\Travelport\\Vehicle\\PaymentRef',
  'BookingTravelerRef' => 'Santosdave\\Travelport\\Vehicle\\BookingTravelerRef',
  'DiscountCardRef' => 'Santosdave\\Travelport\\Vehicle\\DiscountCardRef',
  'DriversLicenseRef' => 'Santosdave\\Travelport\\Vehicle\\DriversLicenseRef',
  'LoyaltyCardRef' => 'Santosdave\\Travelport\\Vehicle\\LoyaltyCardRef',
  'typeRemark' => 'Santosdave\\Travelport\\Vehicle\\typeRemark',
  'UnassociatedRemark' => 'Santosdave\\Travelport\\Vehicle\\UnassociatedRemark',
  'typeRemarkWithTravelerRef' => 'Santosdave\\Travelport\\Vehicle\\typeRemarkWithTravelerRef',
  'CustomerID' => 'Santosdave\\Travelport\\Vehicle\\CustomerID',
  'BaseReservation' => 'Santosdave\\Travelport\\Vehicle\\BaseReservation',
  'MCO' => 'Santosdave\\Travelport\\Vehicle\\MCO',
  'MCOText' => 'Santosdave\\Travelport\\Vehicle\\MCOText',
  'typeFreeFormText' => 'Santosdave\\Travelport\\Vehicle\\typeFreeFormText',
  'MCOPriceData' => 'Santosdave\\Travelport\\Vehicle\\MCOPriceData',
  'PassengerInfo' => 'Santosdave\\Travelport\\Vehicle\\PassengerInfo',
  'MCOInformation' => 'Santosdave\\Travelport\\Vehicle\\MCOInformation',
  'MCOExchangeInfo' => 'Santosdave\\Travelport\\Vehicle\\MCOExchangeInfo',
  'MCOFeeInfo' => 'Santosdave\\Travelport\\Vehicle\\MCOFeeInfo',
  'MCORemark' => 'Santosdave\\Travelport\\Vehicle\\MCORemark',
  'StockControl' => 'Santosdave\\Travelport\\Vehicle\\StockControl',
  'ExchangedCoupon' => 'Santosdave\\Travelport\\Vehicle\\ExchangedCoupon',
  'typeTaxInfo' => 'Santosdave\\Travelport\\Vehicle\\typeTaxInfo',
  'TaxDetail' => 'Santosdave\\Travelport\\Vehicle\\TaxDetail',
  'MetaData' => 'Santosdave\\Travelport\\Vehicle\\MetaData',
  'RoleInfo' => 'Santosdave\\Travelport\\Vehicle\\RoleInfo',
  'OSI' => 'Santosdave\\Travelport\\Vehicle\\OSI',
  'Segment' => 'Santosdave\\Travelport\\Vehicle\\Segment',
  'TravelSegment' => 'Santosdave\\Travelport\\Vehicle\\TravelSegment',
  'SearchEvent' => 'Santosdave\\Travelport\\Vehicle\\SearchEvent',
  'SearchTicketing' => 'Santosdave\\Travelport\\Vehicle\\SearchTicketing',
  'SearchPassenger' => 'Santosdave\\Travelport\\Vehicle\\SearchPassenger',
  'SpecialEquipment' => 'Santosdave\\Travelport\\Vehicle\\SpecialEquipment',
  'ContinuityCheckOverride' => 'Santosdave\\Travelport\\Vehicle\\ContinuityCheckOverride',
  'typeAgentInfo' => 'Santosdave\\Travelport\\Vehicle\\typeAgentInfo',
  'typeResultMessage' => 'Santosdave\\Travelport\\Vehicle\\typeResultMessage',
  'Location' => 'Santosdave\\Travelport\\Vehicle\\Location',
  'typeSearchTimeSpec' => 'Santosdave\\Travelport\\Vehicle\\typeSearchTimeSpec',
  'typeStructuredAddress' => 'Santosdave\\Travelport\\Vehicle\\typeStructuredAddress',
  'typeTimeRange' => 'Santosdave\\Travelport\\Vehicle\\typeTimeRange',
  'typeRateDescription' => 'Santosdave\\Travelport\\Vehicle\\typeRateDescription',
  'MediaItem' => 'Santosdave\\Travelport\\Vehicle\\MediaItem',
  'PointOfSale' => 'Santosdave\\Travelport\\Vehicle\\PointOfSale',
  'BookingTravelerInfo' => 'Santosdave\\Travelport\\Vehicle\\BookingTravelerInfo',
  'TravelInfo' => 'Santosdave\\Travelport\\Vehicle\\TravelInfo',
  'BookingSource' => 'Santosdave\\Travelport\\Vehicle\\BookingSource',
  'typeSearchLocation' => 'Santosdave\\Travelport\\Vehicle\\typeSearchLocation',
  'typeTimeSpec' => 'Santosdave\\Travelport\\Vehicle\\typeTimeSpec',
  'typeSpecificTime' => 'Santosdave\\Travelport\\Vehicle\\typeSpecificTime',
  'typeFlexibleTimeSpec' => 'Santosdave\\Travelport\\Vehicle\\typeFlexibleTimeSpec',
  'SearchExtraDays' => 'Santosdave\\Travelport\\Vehicle\\SearchExtraDays',
  'typePassengerType' => 'Santosdave\\Travelport\\Vehicle\\typePassengerType',
  'Guarantee' => 'Santosdave\\Travelport\\Vehicle\\Guarantee',
  'OtherGuaranteeInfo' => 'Santosdave\\Travelport\\Vehicle\\OtherGuaranteeInfo',
  'Payment' => 'Santosdave\\Travelport\\Vehicle\\Payment',
  'ServiceRuleType' => 'Santosdave\\Travelport\\Vehicle\\ServiceRuleType',
  'ApplicationRules' => 'Santosdave\\Travelport\\Vehicle\\ApplicationRules',
  'ApplicationLevel' => 'Santosdave\\Travelport\\Vehicle\\ApplicationLevel',
  'ApplicationLimits' => 'Santosdave\\Travelport\\Vehicle\\ApplicationLimits',
  'ModifyRules' => 'Santosdave\\Travelport\\Vehicle\\ModifyRules',
  'ModifyRule' => 'Santosdave\\Travelport\\Vehicle\\ModifyRule',
  'SecondaryTypeRules' => 'Santosdave\\Travelport\\Vehicle\\SecondaryTypeRules',
  'SecondaryTypeRule' => 'Santosdave\\Travelport\\Vehicle\\SecondaryTypeRule',
  'OptionalServiceApplicationLimitType' => 'Santosdave\\Travelport\\Vehicle\\OptionalServiceApplicationLimitType',
  'FormattedTextTextType' => 'Santosdave\\Travelport\\Vehicle\\FormattedTextTextType',
  'CorporateDiscountID' => 'Santosdave\\Travelport\\Vehicle\\CorporateDiscountID',
  'AgencyContactInfo' => 'Santosdave\\Travelport\\Vehicle\\AgencyContactInfo',
  'typeLocation' => 'Santosdave\\Travelport\\Vehicle\\typeLocation',
  'typeProfileRef' => 'Santosdave\\Travelport\\Vehicle\\typeProfileRef',
  'ServiceFeeTaxInfo' => 'Santosdave\\Travelport\\Vehicle\\ServiceFeeTaxInfo',
  'ServiceFeeInfo' => 'Santosdave\\Travelport\\Vehicle\\ServiceFeeInfo',
  'LinkedUniversalRecord' => 'Santosdave\\Travelport\\Vehicle\\LinkedUniversalRecord',
  'typeDateRange' => 'Santosdave\\Travelport\\Vehicle\\typeDateRange',
  'MarketingInformation' => 'Santosdave\\Travelport\\Vehicle\\MarketingInformation',
  'Postscript' => 'Santosdave\\Travelport\\Vehicle\\Postscript',
  'typeAgencyHierarchyReference' => 'Santosdave\\Travelport\\Vehicle\\typeAgencyHierarchyReference',
  'typeAgencyHierarchyLongReference' => 'Santosdave\\Travelport\\Vehicle\\typeAgencyHierarchyLongReference',
  'DriversLicense' => 'Santosdave\\Travelport\\Vehicle\\DriversLicense',
  'typeAssociatedRemarkWithSegmentRef' => 'Santosdave\\Travelport\\Vehicle\\typeAssociatedRemarkWithSegmentRef',
  'typeAssociatedRemark' => 'Santosdave\\Travelport\\Vehicle\\typeAssociatedRemark',
  'ShopInformation' => 'Santosdave\\Travelport\\Vehicle\\ShopInformation',
  'SearchRequest' => 'Santosdave\\Travelport\\Vehicle\\SearchRequest',
  'FlightsOffered' => 'Santosdave\\Travelport\\Vehicle\\FlightsOffered',
  'PolicyInformation' => 'Santosdave\\Travelport\\Vehicle\\PolicyInformation',
  'ReasonCode' => 'Santosdave\\Travelport\\Vehicle\\ReasonCode',
  'AgencyInformation' => 'Santosdave\\Travelport\\Vehicle\\AgencyInformation',
  'AccountInformation' => 'Santosdave\\Travelport\\Vehicle\\AccountInformation',
  'TravelerInformation' => 'Santosdave\\Travelport\\Vehicle\\TravelerInformation',
  'EmergencyContact' => 'Santosdave\\Travelport\\Vehicle\\EmergencyContact',
  'CustomProfileInformation' => 'Santosdave\\Travelport\\Vehicle\\CustomProfileInformation',
  'FileFinishingInfo' => 'Santosdave\\Travelport\\Vehicle\\FileFinishingInfo',
  'BillingPointOfSaleInfo' => 'Santosdave\\Travelport\\Vehicle\\BillingPointOfSaleInfo',
  'AgentIDOverride' => 'Santosdave\\Travelport\\Vehicle\\AgentIDOverride',
  'OverridePCC' => 'Santosdave\\Travelport\\Vehicle\\OverridePCC',
  'typeKeyword' => 'Santosdave\\Travelport\\Vehicle\\typeKeyword',
  'typeSubKey' => 'Santosdave\\Travelport\\Vehicle\\typeSubKey',
  'typeOTAKeyword' => 'Santosdave\\Travelport\\Vehicle\\typeOTAKeyword',
  'typeOTASubKey' => 'Santosdave\\Travelport\\Vehicle\\typeOTASubKey',
  'Keyword' => 'Santosdave\\Travelport\\Vehicle\\Keyword',
  'BookingDates' => 'Santosdave\\Travelport\\Vehicle\\BookingDates',
  'PaymentRestriction' => 'Santosdave\\Travelport\\Vehicle\\PaymentRestriction',
  'RequiredField' => 'Santosdave\\Travelport\\Vehicle\\RequiredField',
  'CardRestriction' => 'Santosdave\\Travelport\\Vehicle\\CardRestriction',
  'AddressRestriction' => 'Santosdave\\Travelport\\Vehicle\\AddressRestriction',
  'SSRInfo' => 'Santosdave\\Travelport\\Vehicle\\SSRInfo',
  'typeNonAirReservationRef' => 'Santosdave\\Travelport\\Vehicle\\typeNonAirReservationRef',
  'typeSegmentRef' => 'Santosdave\\Travelport\\Vehicle\\typeSegmentRef',
  'InvoiceRemark' => 'Santosdave\\Travelport\\Vehicle\\InvoiceRemark',
  'RequestKeyMappings' => 'Santosdave\\Travelport\\Vehicle\\RequestKeyMappings',
  'KeyMapping' => 'Santosdave\\Travelport\\Vehicle\\KeyMapping',
  'ReservationName' => 'Santosdave\\Travelport\\Vehicle\\ReservationName',
  'NameOverride' => 'Santosdave\\Travelport\\Vehicle\\NameOverride',
  'APIProvider' => 'Santosdave\\Travelport\\Vehicle\\APIProvider',
  'AvailablePseudoCityCode' => 'Santosdave\\Travelport\\Vehicle\\AvailablePseudoCityCode',
  'TransactionType' => 'Santosdave\\Travelport\\Vehicle\\TransactionType',
  'Air' => 'Santosdave\\Travelport\\Vehicle\\Air',
  'typeTransactionsAllowed' => 'Santosdave\\Travelport\\Vehicle\\typeTransactionsAllowed',
  'typeBookingTransactionsAllowed' => 'Santosdave\\Travelport\\Vehicle\\typeBookingTransactionsAllowed',
  'ThirdPartyInformation' => 'Santosdave\\Travelport\\Vehicle\\ThirdPartyInformation',
  'TravelComplianceData' => 'Santosdave\\Travelport\\Vehicle\\TravelComplianceData',
  'PolicyCompliance' => 'Santosdave\\Travelport\\Vehicle\\PolicyCompliance',
  'ContractCompliance' => 'Santosdave\\Travelport\\Vehicle\\ContractCompliance',
  'PreferredSupplier' => 'Santosdave\\Travelport\\Vehicle\\PreferredSupplier',
  'LoyaltyProgram' => 'Santosdave\\Travelport\\Vehicle\\LoyaltyProgram',
  'typeErrorInfo' => 'Santosdave\\Travelport\\Vehicle\\typeErrorInfo',
  'PermittedProviders' => 'Santosdave\\Travelport\\Vehicle\\PermittedProviders',
  'ReviewBooking' => 'Santosdave\\Travelport\\Vehicle\\ReviewBooking',
  'typeCreditCardType' => 'Santosdave\\Travelport\\Vehicle\\typeCreditCardType',
  'PersonalGeography' => 'Santosdave\\Travelport\\Vehicle\\PersonalGeography',
  'Group' => 'Santosdave\\Travelport\\Vehicle\\Group',
  'SSRRef' => 'Santosdave\\Travelport\\Vehicle\\SSRRef',
  'ConsolidatorRemark' => 'Santosdave\\Travelport\\Vehicle\\ConsolidatorRemark',
  'PseudoCityCode' => 'Santosdave\\Travelport\\Vehicle\\PseudoCityCode',
  'BaseAsyncProviderSpecificResponse' => 'Santosdave\\Travelport\\Vehicle\\BaseAsyncProviderSpecificResponse',
  'typeProviderReservationDetail' => 'Santosdave\\Travelport\\Vehicle\\typeProviderReservationDetail',
  'CabinClass' => 'Santosdave\\Travelport\\Vehicle\\CabinClass',
  'SeatAttributes' => 'Santosdave\\Travelport\\Vehicle\\SeatAttributes',
  'SeatAttribute' => 'Santosdave\\Travelport\\Vehicle\\SeatAttribute',
  'typeKeyBasedReference' => 'Santosdave\\Travelport\\Vehicle\\typeKeyBasedReference',
  'InvoiceData' => 'Santosdave\\Travelport\\Vehicle\\InvoiceData',
  'BookingTravelerInformation' => 'Santosdave\\Travelport\\Vehicle\\BookingTravelerInformation',
  'OwnershipChange' => 'Santosdave\\Travelport\\Vehicle\\OwnershipChange',
  'IndustryStandardSSR' => 'Santosdave\\Travelport\\Vehicle\\IndustryStandardSSR',
  'PaymentAdvice' => 'Santosdave\\Travelport\\Vehicle\\PaymentAdvice',
  'EmailNotification' => 'Santosdave\\Travelport\\Vehicle\\EmailNotification',
  'typeTax' => 'Santosdave\\Travelport\\Vehicle\\typeTax',
  'typeFeeInfo' => 'Santosdave\\Travelport\\Vehicle\\typeFeeInfo',
  'TaxInfoRef' => 'Santosdave\\Travelport\\Vehicle\\TaxInfoRef',
  'QueuePlace' => 'Santosdave\\Travelport\\Vehicle\\QueuePlace',
  'QueueSelector' => 'Santosdave\\Travelport\\Vehicle\\QueueSelector',
  'typePolicyCodesList' => 'Santosdave\\Travelport\\Vehicle\\typePolicyCodesList',
  'IncludedInBase' => 'Santosdave\\Travelport\\Vehicle\\IncludedInBase',
  'PointOfCommencement' => 'Santosdave\\Travelport\\Vehicle\\PointOfCommencement',
  'PriceMatchError' => 'Santosdave\\Travelport\\Vehicle\\PriceMatchError',
  'BaseReq' => 'Santosdave\\Travelport\\Vehicle\\BaseReq',
  'BaseCoreReq' => 'Santosdave\\Travelport\\Vehicle\\BaseCoreReq',
  'BaseSearchReq' => 'Santosdave\\Travelport\\Vehicle\\BaseSearchReq',
  'BaseCoreSearchReq' => 'Santosdave\\Travelport\\Vehicle\\BaseCoreSearchReq',
  'BaseSearchRsp' => 'Santosdave\\Travelport\\Vehicle\\BaseSearchRsp',
  'BaseRsp' => 'Santosdave\\Travelport\\Vehicle\\BaseRsp',
  'BaseCreateReservationReq' => 'Santosdave\\Travelport\\Vehicle\\BaseCreateReservationReq',
  'ErrorInfo' => 'Santosdave\\Travelport\\Vehicle\\ErrorInfo',
  'BaseCreateWithFormOfPaymentReq' => 'Santosdave\\Travelport\\Vehicle\\BaseCreateWithFormOfPaymentReq',
  'VehicleReservation' => 'Santosdave\\Travelport\\Vehicle\\VehicleReservation',
  'PaymentInformation' => 'Santosdave\\Travelport\\Vehicle\\PaymentInformation',
  'VehicleDateLocation' => 'Santosdave\\Travelport\\Vehicle\\VehicleDateLocation',
  'typeVehicleVendorLocation' => 'Santosdave\\Travelport\\Vehicle\\typeVehicleVendorLocation',
  'Vehicle' => 'Santosdave\\Travelport\\Vehicle\\Vehicle',
  'VehicleRate' => 'Santosdave\\Travelport\\Vehicle\\VehicleRate',
  'PricedEquip' => 'Santosdave\\Travelport\\Vehicle\\PricedEquip',
  'Equipment' => 'Santosdave\\Travelport\\Vehicle\\Equipment',
  'Charge' => 'Santosdave\\Travelport\\Vehicle\\Charge',
  'SupplierRate' => 'Santosdave\\Travelport\\Vehicle\\SupplierRate',
  'typeVehicleRates' => 'Santosdave\\Travelport\\Vehicle\\typeVehicleRates',
  'RateModifiers' => 'Santosdave\\Travelport\\Vehicle\\RateModifiers',
  'VehicleSpecialRequest' => 'Santosdave\\Travelport\\Vehicle\\VehicleSpecialRequest',
  'VehicleSearchModifiers' => 'Santosdave\\Travelport\\Vehicle\\VehicleSearchModifiers',
  'PermittedVendors' => 'Santosdave\\Travelport\\Vehicle\\PermittedVendors',
  'ProhibitedVendors' => 'Santosdave\\Travelport\\Vehicle\\ProhibitedVendors',
  'typeVehicleSearchDistance' => 'Santosdave\\Travelport\\Vehicle\\typeVehicleSearchDistance',
  'VehicleType' => 'Santosdave\\Travelport\\Vehicle\\VehicleType',
  'VehicleModifier' => 'Santosdave\\Travelport\\Vehicle\\VehicleModifier',
  'Vendor' => 'Santosdave\\Travelport\\Vehicle\\Vendor',
  'LocationInfo' => 'Santosdave\\Travelport\\Vehicle\\LocationInfo',
  'VehiclePolicy' => 'Santosdave\\Travelport\\Vehicle\\VehiclePolicy',
  'VendorInfo' => 'Santosdave\\Travelport\\Vehicle\\VendorInfo',
  'VehicleDetail' => 'Santosdave\\Travelport\\Vehicle\\VehicleDetail',
  'VehicleDisclaimer' => 'Santosdave\\Travelport\\Vehicle\\VehicleDisclaimer',
  'typePickupDateLocation' => 'Santosdave\\Travelport\\Vehicle\\typePickupDateLocation',
  'VehicleLocation' => 'Santosdave\\Travelport\\Vehicle\\VehicleLocation',
  'LocationInformation' => 'Santosdave\\Travelport\\Vehicle\\LocationInformation',
  'typePaymentInformation' => 'Santosdave\\Travelport\\Vehicle\\typePaymentInformation',
  'typeRateHostIndicator' => 'Santosdave\\Travelport\\Vehicle\\typeRateHostIndicator',
  'typeRateInfo' => 'Santosdave\\Travelport\\Vehicle\\typeRateInfo',
  'typeRentalPeriod' => 'Santosdave\\Travelport\\Vehicle\\typeRentalPeriod',
  'typeDepositGuarantee' => 'Santosdave\\Travelport\\Vehicle\\typeDepositGuarantee',
  'typeStartEndTime' => 'Santosdave\\Travelport\\Vehicle\\typeStartEndTime',
  'typeVehicleCharge' => 'Santosdave\\Travelport\\Vehicle\\typeVehicleCharge',
  'typeVehicleRateDescription' => 'Santosdave\\Travelport\\Vehicle\\typeVehicleRateDescription',
  'CollectionAddress' => 'Santosdave\\Travelport\\Vehicle\\CollectionAddress',
  'DeliveryAddress' => 'Santosdave\\Travelport\\Vehicle\\DeliveryAddress',
  'FlightArrivalInformation' => 'Santosdave\\Travelport\\Vehicle\\FlightArrivalInformation',
  'VehiclePickupLocation' => 'Santosdave\\Travelport\\Vehicle\\VehiclePickupLocation',
  'VehicleSearchId' => 'Santosdave\\Travelport\\Vehicle\\VehicleSearchId',
  'VehicleWithMediaItems' => 'Santosdave\\Travelport\\Vehicle\\VehicleWithMediaItems',
  'RateInclusions' => 'Santosdave\\Travelport\\Vehicle\\RateInclusions',
  'IncludedItem' => 'Santosdave\\Travelport\\Vehicle\\IncludedItem',
  'VehicleRateInfo' => 'Santosdave\\Travelport\\Vehicle\\VehicleRateInfo',
  'AssociatedRemark' => 'Santosdave\\Travelport\\Vehicle\\AssociatedRemark',
  'VehicleReturnDateLocation' => 'Santosdave\\Travelport\\Vehicle\\VehicleReturnDateLocation',
  'VehiclePickupDateLocation' => 'Santosdave\\Travelport\\Vehicle\\VehiclePickupDateLocation',
  'VehicleTypeIdentifier' => 'Santosdave\\Travelport\\Vehicle\\VehicleTypeIdentifier',
  'typeVehicleLocationInformation' => 'Santosdave\\Travelport\\Vehicle\\typeVehicleLocationInformation',
  'DriverInfo' => 'Santosdave\\Travelport\\Vehicle\\DriverInfo',
  'typeRateVariance' => 'Santosdave\\Travelport\\Vehicle\\typeRateVariance',
  'VehicleSearchAvailabilityReq' => 'Santosdave\\Travelport\\Vehicle\\VehicleSearchAvailabilityReq',
  'VehicleSearchAvailabilityRsp' => 'Santosdave\\Travelport\\Vehicle\\VehicleSearchAvailabilityRsp',
  'VehicleLocationDetailReq' => 'Santosdave\\Travelport\\Vehicle\\VehicleLocationDetailReq',
  'VehicleLocationDetailRsp' => 'Santosdave\\Travelport\\Vehicle\\VehicleLocationDetailRsp',
  'VehicleRetrieveReq' => 'Santosdave\\Travelport\\Vehicle\\VehicleRetrieveReq',
  'VehicleRetrieveRsp' => 'Santosdave\\Travelport\\Vehicle\\VehicleRetrieveRsp',
  'VehicleRulesReq' => 'Santosdave\\Travelport\\Vehicle\\VehicleRulesReq',
  'VehicleRulesLookup' => 'Santosdave\\Travelport\\Vehicle\\VehicleRulesLookup',
  'VehicleRulesRsp' => 'Santosdave\\Travelport\\Vehicle\\VehicleRulesRsp',
  'StartEndTimes' => 'Santosdave\\Travelport\\Vehicle\\StartEndTimes',
  'RentalPeriodRules' => 'Santosdave\\Travelport\\Vehicle\\RentalPeriodRules',
  'PrePayCancelInfo' => 'Santosdave\\Travelport\\Vehicle\\PrePayCancelInfo',
  'PaymentRule' => 'Santosdave\\Travelport\\Vehicle\\PaymentRule',
  'VehicleLocationReq' => 'Santosdave\\Travelport\\Vehicle\\VehicleLocationReq',
  'VehicleLocationRsp' => 'Santosdave\\Travelport\\Vehicle\\VehicleLocationRsp',
  'VehicleKeywordReq' => 'Santosdave\\Travelport\\Vehicle\\VehicleKeywordReq',
  'VehicleKeywordRsp' => 'Santosdave\\Travelport\\Vehicle\\VehicleKeywordRsp',
  'BaseVehicleSearchAvailabilityReq' => 'Santosdave\\Travelport\\Vehicle\\BaseVehicleSearchAvailabilityReq',
  'BaseVehicleSearchAvailabilityRsp' => 'Santosdave\\Travelport\\Vehicle\\BaseVehicleSearchAvailabilityRsp',
  'VehicleUpsellSearchAvailabilityReq' => 'Santosdave\\Travelport\\Vehicle\\VehicleUpsellSearchAvailabilityReq',
  'VehicleUpsellSearchAvailabilityRsp' => 'Santosdave\\Travelport\\Vehicle\\VehicleUpsellSearchAvailabilityRsp',
  'VehicleMediaLinksReq' => 'Santosdave\\Travelport\\Vehicle\\VehicleMediaLinksReq',
  'VehicleMediaLinksRsp' => 'Santosdave\\Travelport\\Vehicle\\VehicleMediaLinksRsp',
);

    /**
     * @param array $options A array of config values
     * @param string $wsdl The wsdl file to use
     */
    public function __construct(array $options = array(), $wsdl = null)
    {
      foreach (self::$classmap as $key => $value) {
        if (!isset($options['classmap'][$key])) {
          $options['classmap'][$key] = $value;
        }
      }
      $options = array_merge(array (
  'features' => 1,
), $options);
      if (!$wsdl) {
        $wsdl = 'D:\efes.to\components\filippo-toso\travelport\builder/../src/Wsdls/vehicle_v49_0/Vehicle.wsdl';
      }
      parent::__construct($wsdl, $options);
    }

    /**
     * @param VehicleMediaLinksReq $parameters
     * @return VehicleMediaLinksRsp
     */
    public function service(VehicleMediaLinksReq $parameters)
    {
      return $this->__soapCall('service', array($parameters));
    }

}